import os
import psycopg2
from dotenv import load_dotenv

load_dotenv()

DB_CONNECTION_STRING = os.getenv("DB_CONNECTION_STRING")

def add_id_column():
    try:
        conn = psycopg2.connect(DB_CONNECTION_STRING)
        cur = conn.cursor()
        
        print("🔧 Adding 'id' column to 'person_roles'...")

        # Check if column exists first
        cur.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'person_roles' AND column_name = 'id';
        """)
        if cur.fetchone():
            print("   Column 'id' already exists.")
        else:
            print("   Dropping existing PK...")
            cur.execute("ALTER TABLE person_roles DROP CONSTRAINT IF EXISTS person_roles_pkey;")
            
            print("   Adding 'id' column...")
            cur.execute("""
                ALTER TABLE person_roles 
                ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
            """)
            
            print("   Adding UNIQUE constraint on (person_id, role_id)...")
            cur.execute("""
                ALTER TABLE person_roles 
                ADD CONSTRAINT person_roles_person_id_role_id_key UNIQUE (person_id, role_id);
            """)
            
            print("✅ Schema updated successfully.")
        
        conn.commit()
        cur.close()
        conn.close()
    except Exception as e:
        print(f"❌ Error: {e}")

if __name__ == "__main__":
    add_id_column()
