import os
import psycopg2
from dotenv import load_dotenv

load_dotenv()

DB_CONNECTION_STRING = os.getenv("DB_CONNECTION_STRING")

def create_schema():
    try:
        conn = psycopg2.connect(DB_CONNECTION_STRING)
        cur = conn.cursor()
        
        print("🚀 Creating Job Inputs Schema...")

        # 1. job_template_inputs
        print("   Creating job_template_inputs table...")
        cur.execute("""
            CREATE TABLE IF NOT EXISTS job_template_inputs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                job_template_id BIGINT REFERENCES job_templates(id) ON DELETE CASCADE,
                tenant_id INTEGER NOT NULL,
                label TEXT NOT NULL,
                key TEXT NOT NULL,
                input_type TEXT DEFAULT 'text', -- text, number, date, photo, select
                is_required BOOLEAN DEFAULT TRUE,
                options JSONB DEFAULT '[]'::jsonb,
                created_at TIMESTAMPTZ DEFAULT NOW(),
                updated_at TIMESTAMPTZ DEFAULT NOW()
            );
        """)

        # 2. job_inputs
        print("   Creating job_inputs table...")
        cur.execute("""
            CREATE TABLE IF NOT EXISTS job_inputs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                job_id BIGINT REFERENCES jobs(id) ON DELETE CASCADE,
                input_definition_id BIGINT REFERENCES job_template_inputs(id) ON DELETE CASCADE,
                value JSONB,
                provided_at TIMESTAMPTZ,
                provided_by UUID REFERENCES auth.users(id),
                created_at TIMESTAMPTZ DEFAULT NOW(),
                updated_at TIMESTAMPTZ DEFAULT NOW()
            );
        """)

        # 3. Enable RLS
        cur.execute("ALTER TABLE job_template_inputs ENABLE ROW LEVEL SECURITY;")
        cur.execute("ALTER TABLE job_inputs ENABLE ROW LEVEL SECURITY;")
        
        # Simple policy for now
        cur.execute("""
            DO $$ 
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies WHERE tablename = 'job_template_inputs' AND policyname = 'enable_all_for_tenant'
                ) THEN
                    CREATE POLICY enable_all_for_tenant ON job_template_inputs
                        USING (tenant_id = (SELECT (current_setting('app.current_tenant'::text))::integer));
                END IF;
            END $$;
        """)

        # For job_inputs, we need to join with jobs to check tenant, but for simplicity in this prototype, 
        # we'll assume if you can see the job, you can see the inputs.
        # Actually, let's just add tenant_id to job_inputs for easier RLS, or rely on a join policy.
        # Adding tenant_id to job_inputs is safer and more performant for RLS.
        
        print("   Adding tenant_id to job_inputs...")
        cur.execute("""
            ALTER TABLE job_inputs 
            ADD COLUMN IF NOT EXISTS tenant_id INTEGER;
        """)
        
        cur.execute("""
            DO $$ 
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies WHERE tablename = 'job_inputs' AND policyname = 'enable_all_for_tenant'
                ) THEN
                    CREATE POLICY enable_all_for_tenant ON job_inputs
                        USING (tenant_id = (SELECT (current_setting('app.current_tenant'::text))::integer));
                END IF;
            END $$;
        """)

        conn.commit()
        print("✅ Schema created successfully.")
        
        cur.close()
        conn.close()
    except Exception as e:
        print(f"❌ Error: {e}")

if __name__ == "__main__":
    create_schema()
