import os
import psycopg2
from dotenv import load_dotenv

load_dotenv()

DB_CONNECTION_STRING = os.getenv("DB_CONNECTION_STRING")

def create_schema():
    try:
        conn = psycopg2.connect(DB_CONNECTION_STRING)
        cur = conn.cursor()
        
        print("🚀 Creating Task Layer Schema...")

        # 1. task_templates
        print("   Creating task_templates table...")
        cur.execute("""
            CREATE TABLE IF NOT EXISTS task_templates (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                job_template_id BIGINT REFERENCES job_templates(id) ON DELETE CASCADE,
                tenant_id INTEGER NOT NULL,
                title TEXT NOT NULL,
                description TEXT,
                is_required BOOLEAN DEFAULT TRUE,
                input_type TEXT DEFAULT 'checkbox', -- checkbox, text, photo, number
                order_index INTEGER DEFAULT 0,
                created_at TIMESTAMPTZ DEFAULT NOW(),
                updated_at TIMESTAMPTZ DEFAULT NOW()
            );
        """)

        # 2. job_tasks
        print("   Creating job_tasks table...")
        cur.execute("""
            CREATE TABLE IF NOT EXISTS job_tasks (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                job_id BIGINT REFERENCES jobs(id) ON DELETE CASCADE,
                task_template_id BIGINT REFERENCES task_templates(id) ON DELETE SET NULL,
                title TEXT NOT NULL,
                status TEXT DEFAULT 'Pending', -- Pending, Complete, Skipped
                completed_at TIMESTAMPTZ,
                completed_by UUID REFERENCES auth.users(id),
                data JSONB DEFAULT '{}'::jsonb,
                created_at TIMESTAMPTZ DEFAULT NOW(),
                updated_at TIMESTAMPTZ DEFAULT NOW()
            );
        """)

        # 3. Enable RLS (Security Hardening - Basic)
        cur.execute("ALTER TABLE task_templates ENABLE ROW LEVEL SECURITY;")
        cur.execute("ALTER TABLE job_tasks ENABLE ROW LEVEL SECURITY;")
        
        # Simple policy for now (allow all for authenticated users in same tenant)
        # In production, we'd be more specific.
        cur.execute("""
            DO $$ 
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies WHERE tablename = 'task_templates' AND policyname = 'enable_all_for_tenant'
                ) THEN
                    CREATE POLICY enable_all_for_tenant ON task_templates
                        USING (tenant_id = (SELECT (current_setting('app.current_tenant'::text))::integer));
                END IF;
            END $$;
        """)

        conn.commit()
        print("✅ Schema created successfully.")
        
        cur.close()
        conn.close()
    except Exception as e:
        print(f"❌ Error: {e}")

if __name__ == "__main__":
    create_schema()
