import os
import psycopg2
from dotenv import load_dotenv

load_dotenv()

DB_CONNECTION_STRING = os.getenv("DB_CONNECTION_STRING")

def create_schema():
    try:
        conn = psycopg2.connect(DB_CONNECTION_STRING)
        cur = conn.cursor()
        
        print("🚀 Creating Service Orchestration Schema...")

        # 1. service_templates (Evolution of job_templates)
        # We will create a new table to be clean.
        print("   Creating service_templates table...")
        cur.execute("""
            CREATE TABLE IF NOT EXISTS service_templates (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tenant_id INTEGER NOT NULL,
                name TEXT NOT NULL,
                description TEXT,
                created_at TIMESTAMPTZ DEFAULT NOW(),
                deleted_at TIMESTAMPTZ
            );
        """)
        
        # 2. service_workflow_steps
        print("   Creating service_workflow_steps table...")
        cur.execute("""
            CREATE TABLE IF NOT EXISTS service_workflow_steps (
                id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
                service_template_id BIGINT REFERENCES service_templates(id) ON DELETE CASCADE,
                step_name TEXT NOT NULL,
                job_type TEXT NOT NULL, -- 'Kitting', 'Field', 'Inspection', 'Invoice'
                is_field_job BOOLEAN DEFAULT FALSE,
                depends_on_step_id UUID REFERENCES service_workflow_steps(id),
                order_index INTEGER DEFAULT 0,
                required_inputs JSONB DEFAULT '[]'::jsonb,
                created_at TIMESTAMPTZ DEFAULT NOW()
            );
        """)

        # 3. Add metadata column to jobs if not exists (it likely exists as jsonb, but let's check/ensure)
        # We need to store step_id in jobs to track lineage.
        # Assuming 'metadata' column exists on jobs table based on previous context, but let's be safe.
        # Actually, previous context showed 'metadata' usage.
        
        conn.commit()
        print("✅ Schema created successfully.")
        
        cur.close()
        conn.close()
    except Exception as e:
        print(f"❌ Error: {e}")

if __name__ == "__main__":
    create_schema()
